/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 trash_and_debris.glb 
Author: mcsteegs (https://sketchfab.com/mcsteegs)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/trash-and-debris-831a2b9fb9cd413abb5f178e8d3eb3f6
Title: Trash and Debris
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/trash_and_debris.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Barriar_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Brick_1_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Brick_2_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Can_1_RustyCans_0.geometry} material={materials.RustyCans} />
      <mesh geometry={nodes.Can_1_Crushed_RustyCans_0.geometry} material={materials.RustyCans} />
      <mesh geometry={nodes.Can_2_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_2_Crushed_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_3_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_3_Crushed_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_4_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_4_Crushed_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_5_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_5_Crushed_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_6_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_6_Crushed_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_7_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_7_Crushed_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_8_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.Can_8_Crushed_Cans_0.geometry} material={materials.Cans} />
      <mesh geometry={nodes.CardboardBox_1_CardboardPaper_0.geometry} material={materials.CardboardPaper} />
      <mesh geometry={nodes.CardboardBox_2_CardboardPaper_0.geometry} material={materials.CardboardPaper} />
      <mesh geometry={nodes.CardboardBox_3_CardboardPaper_0.geometry} material={materials.CardboardPaper} />
      <mesh geometry={nodes.CardboardBox_4_CardboardPaper_0.geometry} material={materials.CardboardPaper} />
      <mesh geometry={nodes.Cardboard_Cutout_1_CardboardPaper_0.geometry} material={materials.CardboardPaper} />
      <mesh geometry={nodes.Cardboard_Cutout_2_CardboardPaper_0.geometry} material={materials.CardboardPaper} />
      <mesh geometry={nodes.Chip_Bag_1_ChipBag_0.geometry} material={materials.ChipBag} />
      <mesh geometry={nodes.Chip_Bag_2_ChipBag_0.geometry} material={materials.ChipBag} />
      <mesh geometry={nodes.Chip_Bag_3_ChipBag_0.geometry} material={materials.ChipBag} />
      <mesh geometry={nodes.Chip_Bag_4_ChipBag_0.geometry} material={materials.ChipBag} />
      <mesh geometry={nodes.Cinder_Block_1_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Cinder_Block_2_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Coffee_Cup_Lid_FastFoodTrash_0.geometry} material={materials.FastFoodTrash} />
      <mesh geometry={nodes.Coffee_Cup_FastFoodTrash_0.geometry} material={materials.FastFoodTrash} />
      <mesh geometry={nodes.Coffee_Cup_Crushed_FastFoodTrash_0.geometry} material={materials.FastFoodTrash} />
      <mesh geometry={nodes.Coffee_Cup_WithLid_FastFoodTrash_0.geometry} material={materials.FastFoodTrash} />
      <mesh geometry={nodes.Concrete_Debris_1_WoodMetal_0.geometry} material={materials.WoodMetal} />
      <mesh geometry={nodes.Concrete_Debris_2_WoodMetal_0.geometry} material={materials.WoodMetal} />
      <mesh geometry={nodes.Condom_1_MiscTrash2_0.geometry} material={materials.MiscTrash2} />
      <mesh geometry={nodes.Condom_2_MiscTrash2_0.geometry} material={materials.MiscTrash2} />
      <mesh geometry={nodes.Flat_Can_1_FlatCans_0.geometry} material={materials.FlatCans} />
      <mesh geometry={nodes.Flat_Can_2_FlatCans_0.geometry} material={materials.FlatCans} />
      <mesh geometry={nodes.Flat_Can_3_FlatCans_0.geometry} material={materials.FlatCans} />
      <mesh geometry={nodes.Flat_Can_4_FlatCans_0.geometry} material={materials.FlatCans} />
      <mesh geometry={nodes.Barriar_cell_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Barriar_cell001_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Barriar_cell002_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Barriar_cell003_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Barriar_cell004_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Barriar_cell005_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Barriar_cell007_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Barriar_cell008_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Barriar_cell009_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Barriar_cell010_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Barriar_cell011_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Fry_Container_FastFoodTrash_0.geometry} material={materials.FastFoodTrash} />
      <mesh geometry={nodes.GasCan_Bottles_0.geometry} material={materials.Bottles} />
      <mesh geometry={nodes.GlassBottle_1_GlassBottles_0.geometry} material={materials.GlassBottles} />
      <mesh geometry={nodes.GlassBottle_1_Broken_GlassBottles_0.geometry} material={materials.GlassBottles} />
      <mesh geometry={nodes.GlassBottle_2_GlassBottles_0.geometry} material={materials.GlassBottles} />
      <mesh geometry={nodes.GlassBottle_2_Broken_GlassBottles_0.geometry} material={materials.GlassBottles} />
      <mesh geometry={nodes.GlassBottle_3_GlassBottles_0.geometry} material={materials.GlassBottles} />
      <mesh geometry={nodes.GlassBottle_3_Broken_GlassBottles_0.geometry} material={materials.GlassBottles} />
      <mesh geometry={nodes.GlassBottle_4_GlassBottles_0.geometry} material={materials.GlassBottles} />
      <mesh geometry={nodes.GlassBottle_4_Broken_GlassBottles_0.geometry} material={materials.GlassBottles} />
      <mesh geometry={nodes.Glass_Shards_1_Glass_Shards_1_0.geometry} material={materials.Glass_Shards_1} />
      <mesh geometry={nodes.Glass_Shards_2_Glass_Shards_1_0.geometry} material={materials.Glass_Shards_1} />
      <mesh geometry={nodes.Litter_1_Litter_1_0.geometry} material={materials.Litter_1} />
      <mesh geometry={nodes.Litter_2_Litter_2_0.geometry} material={materials.Litter_2} scale={0.705} />
      <mesh geometry={nodes.Mask_1_MiscTrash2_0.geometry} material={materials.MiscTrash2} />
      <mesh geometry={nodes.Mask_2_MiscTrash2_0.geometry} material={materials.MiscTrash2} />
      <mesh geometry={nodes.News_1_Newspaper_0.geometry} material={materials.Newspaper} />
      <mesh geometry={nodes.News_2_Newspaper_0.geometry} material={materials.Newspaper} />
      <mesh geometry={nodes.News_3_Newspaper_0.geometry} material={materials.Newspaper} />
      <mesh geometry={nodes.News_Stack_Newspaper_0.geometry} material={materials.Newspaper} />
      <mesh geometry={nodes.Paper_1_CardboardPaper_0.geometry} material={materials.CardboardPaper} />
      <mesh geometry={nodes.Paper_2_CardboardPaper_0.geometry} material={materials.CardboardPaper} />
      <mesh geometry={nodes.Paper_Bag_1_FastFoodTrash_0.geometry} material={materials.FastFoodTrash} />
      <mesh geometry={nodes.Paper_Bag_2_FastFoodTrash_0.geometry} material={materials.FastFoodTrash} />
      <mesh geometry={nodes.Paper_Bag_3_FastFoodTrash_0.geometry} material={materials.FastFoodTrash} />
      <mesh geometry={nodes.Pills_1_MiscTrash1_0.geometry} material={materials.MiscTrash1} />
      <mesh geometry={nodes.Pills_2_MiscTrash1_0.geometry} material={materials.MiscTrash1} />
      <mesh geometry={nodes.Rebar_WoodMetal_0.geometry} material={materials.WoodMetal} />
      <mesh geometry={nodes.ShampooBottle_Bottles_0.geometry} material={materials.Bottles} />
      <mesh geometry={nodes.Sheet_Metal_1_WoodMetal_0.geometry} material={materials.WoodMetal} />
      <mesh geometry={nodes.Sheet_Metal_2_WoodMetal_0.geometry} material={materials.WoodMetal} />
      <mesh geometry={nodes.SoapBottle_Bottles_0.geometry} material={materials.Bottles} />
      <mesh geometry={nodes.Soda_Cup_FastFoodTrash_0.geometry} material={materials.FastFoodTrash} />
      <mesh geometry={nodes.Soda_Cup_Crushed_FastFoodTrash_0.geometry} material={materials.FastFoodTrash} />
      <mesh geometry={nodes.Soda_Cup_Lid_FastFoodTrash_0.geometry} material={materials.FastFoodTrash} />
      <mesh geometry={nodes.Tin_1_MiscTrash1_0.geometry} material={materials.MiscTrash1} />
      <mesh geometry={nodes.Tin_2_MiscTrash1_0.geometry} material={materials.MiscTrash1} />
      <mesh geometry={nodes.Tin_3_MiscTrash1_0.geometry} material={materials.MiscTrash1} />
      <mesh geometry={nodes.Tin_4_MiscTrash1_0.geometry} material={materials.MiscTrash1} />
      <mesh geometry={nodes.TrashBag_1_TrashBag_0.geometry} material={materials.TrashBag} />
      <mesh geometry={nodes.TrashBag_2_TrashBag_0.geometry} material={materials.TrashBag} />
      <mesh geometry={nodes.WaterBottle_Bottles_0.geometry} material={materials.Bottles} />
      <mesh geometry={nodes.Wheel_1_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Wheel_2_BrickWheel_0.geometry} material={materials.BrickWheel} />
      <mesh geometry={nodes.Wooden_Plank_1_WoodMetal_0.geometry} material={materials.WoodMetal} />
      <mesh geometry={nodes.Wooden_Plank_2_WoodMetal_0.geometry} material={materials.WoodMetal} />
      <mesh geometry={nodes.Wooden_Plank_3_WoodMetal_0.geometry} material={materials.WoodMetal} />
    </group>
  )
}

useGLTF.preload('/trash_and_debris.glb')
